site_name: Service Level Helper (slh)
repo_url: https://github.com/lucasloureiror/slh
repo_name: slh

theme: 
  name: material
  palette:
     
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: light blue
      toggle:
        icon: material/lightbulb-outline
        name: light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      accent: blue
      toggle:
        icon: material/lightbulb
        name: dark mode

     

  language: en
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate

nav:
  - Home: index.md
  - Installation: install.md
  - Usage: usage.md
  - Probe Frequency Calculation Algorithm: probe.md
  - FAQ: faq.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js