name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{github.ref_name}}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: stable
        check-latest: true
    
    - name: mod tidy
      run: go mod tidy

    - name: Build
      run: echo $VERSION &&go build

  test:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{github.ref_name}}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: stable
        check-latest: true

    - name: mod tidy
      run: go mod tidy

    - name: Test
      run: go test ./...